# Generated by Django 2.2a1 on 2019-01-27 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='users',
            field=models.ManyToManyField(related_name='tenants', through='tenants.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='tenants', to='synczones.Zone'),
        ),
    ]
