# Generated by Django 2.2a1 on 2019-01-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20190127_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='level',
            field=models.TextField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='ADMIN', max_length=5),
            preserve_default=False,
        ),
    ]
