# Generated by Django 2.2a1 on 2019-01-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name', models.CharField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
