# Generated by Django 2.2b1 on 2019-03-25 23:06

from django.db import migrations, IntegrityError

from dino.pdns_api import pdns


def combine_names(apps, schema_editor):
    Zone = apps.get_model('synczones', 'Zone')

    for zone in Zone.objects.filter(name__contains='xn--'):
        decoded_name = pdns._decode_name(zone.name)
        new_zone = Zone.objects.get_or_create(name=decoded_name)

        for tenant in zone.tenants.all():
            new_zone.tenants.add(tenant)

        zone.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('synczones', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
